version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # Volumes are not needed when using watch, but the node_modules volume is still useful
    volumes:
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    # Add the develop section for watch mode
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    # Override the default command to run the dev server
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Volumes are not needed when using watch
    # volumes:
    #   - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db/nestling_db
    depends_on:
      - db
    # Add the develop section for watch mode
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    # Override the default command to run uvicorn with reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ww870411
      - POSTGRES_PASSWORD=w870411w
      - POSTGRES_DB=nestling_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  frontend_node_modules:
