export const reportTemplate = [
  // --- 设备参数 ---
  {
    id: 3,
    category: '设备参数',
    name: '发电机组容量',
    unit: '万kW',
    type: 'basic',
    formula: null,
  },
  {
    id: 4,
    category: '设备参数',
    name: '燃煤锅炉装机容量',
    unit: 'MW',
    type: 'basic',
    formula: null,
  },
  {
    id: 5,
    category: '设备参数',
    name: '电锅炉/热泵装机容量',
    unit: 'MW',
    type: 'basic',
    formula: null,
  },

  // --- 产量 ---
  {
    id: 6,
    category: '产量',
    name: '发电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
  },
  {
    id: 7,
    category: '产量',
    name: '供热量↓',
    unit: 'GJ',
    type: 'calculated',
    formula: 'VAL(8)+VAL(9)+VAL(10)+VAL(11)+VAL(12)',
  },
  {
    id: 8,
    category: '产量',
    name: '其中：1.供汽量',
    unit: '吨',
    type: 'basic',
    formula: null,
  },
  {
    id: 9,
    category: '产量',
    name: '2.高温水供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
  },
  {
    id: 10,
    category: '产量',
    name: '3.低真空供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
  },
  {
    id: 11,
    category: '产量',
    name: '4.低温水供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
  },
  {
    id: 12,
    category: '产量',
    name: '5.电锅炉/热泵供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
  },

  // --- 销量 ---
  {
    id: 13,
    category: '销量',
    name: '售电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
  },
  {
    id: 14,
    category: '销量',
    name: '售汽量',
    unit: '吨',
    type: 'basic',
    formula: null,
  },
  {
    id: 18,
    category: '销量',
    name: '期末供暖收费面积',
    unit: '㎡',
    type: 'calculated',
    formula: 'VAL(19)+VAL(20)+VAL(21)+VAL(22)+VAL(23)',
  },
  {
    id: 19,
    category: '销量',
    name: '1.汽站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
  },
  {
    id: 20,
    category: '销量',
    name: '2.高温水站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
  },
  {
    id: 21,
    category: '销量',
    name: '3.低真空站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
  },
  {
    id: 22,
    category: '销量',
    name: '4.低温水供热面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
  },
  {
    id: 23,
    category: '销量',
    name: '5.电锅炉/热泵面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
  },

  // --- 经济指标 ---
  {
    id: 94,
    category: '经济指标',
    name: '供热发电收入',
    unit: '万元',
    type: 'calculated',
    formula: 'VAL(95)+VAL(97)+VAL(99)+VAL(101)',
  },
  {
    id: 95,
    category: '经济指标',
    name: '暖收入',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 97,
    category: '经济指标',
    name: '电收入',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 99,
    category: '经济指标',
    name: '售汽收入',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 101,
    category: '经济指标',
    name: '售高温水收入',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 109,
    category: '经济指标',
    name: '毛利',
    unit: '万元',
    type: 'calculated',
    formula: 'VAL(94)-VAL(103)-VAL(105)-VAL(107)',
  },
  {
    id: 103,
    category: '经济指标',
    name: '购热成本',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 105,
    category: '经济指标',
    name: '煤成本',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
  {
    id: 107,
    category: '经济指标',
    name: '购电成本',
    unit: '万元',
    type: 'basic',
    formula: null,
  },
];
