// templates/groupTemplate.js

/**
 * 新版字段配置 (fieldConfig)
 * 
 * 结构变更说明:
 * 1.  ID系统: 所有字段ID已从字符串（如 'name'）更改为唯一的数字ID（从1001开始）。
 * 2.  扁平化结构: 原来的 'monthlyData' 分组已被移除。每个月份的'计划'和'同期'现在都是拥有独立ID的顶级字段。
 *    - 例如，'10月-计划' 的ID为 2001，'11月-计划' 的ID为 2003，以此类推。
 * 3.  计算字段: 增加了 'type' 和 'formula' 属性。
 *    - type: 'basic' (基础字段，用户可直接输入) 或 'calculated' (计算字段)。
 *    - formula: 使用 VAL(id) 格式定义计算逻辑。
 */
export const fieldConfig = [
  // --- 基础信息列 (ID: 1001-1002) ---
  {
    id: 1001,
    name: 'name',
    label: '指标名称',
    type: 'basic',
    component: 'label',
    width: 250,
    fixed: true,
  },
  {
    id: 1002,
    name: 'unit',
    label: '计量单位',
    type: 'basic',
    component: 'label',
    width: 100,
    fixed: true,
  },

  // --- 集团全口径 (ID: 1003-1005) ---
  { id: 1003, name: 'group.plan', label: '集团全口径-本期计划', type: 'basic', component: 'display', width: 140 },
  { id: 1004, name: 'group.samePeriod', label: '集团全口径-同期完成', type: 'basic', component: 'display', width: 140 },
  { id: 1005, name: 'group.diffRate', label: '集团全口径-差异率', type: 'basic', component: 'display', width: 140 },

  // --- 主城区 (ID: 1006-1008) ---
  { id: 1006, name: 'downtown.plan', label: '主城区-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1007, name: 'downtown.samePeriod', label: '主城区-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1008, name: 'downtown.diffRate', label: '主城区-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 北海汇总 (ID: 1009-1011) ---
  { id: 1009, name: 'beihai.plan', label: '北海汇总-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1010, name: 'beihai.samePeriod', label: '北海汇总-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1011, name: 'beihai.diffRate', label: '北海汇总-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 香海 (ID: 1012-1014) ---
  { id: 1012, name: 'xianghai.plan', label: '香海-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1013, name: 'xianghai.samePeriod', label: '香海-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1014, name: 'xianghai.diffRate', label: '香海-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 金州 (ID: 1015-1017) ---
  { id: 1015, name: 'jinzhou.plan', label: '金州-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1016, name: 'jinzhou.samePeriod', label: '金州-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1017, name: 'jinzhou.diffRate', label: '金州-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 北方 (ID: 1018-1020) ---
  { id: 1018, name: 'beifang.plan', label: '北方-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1019, name: 'beifang.samePeriod', label: '北方-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1020, name: 'beifang.diffRate', label: '北方-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 金普 (ID: 1021-1023) ---
  { id: 1021, name: 'jinpu.plan', label: '金普-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1022, name: 'jinpu.samePeriod', label: '金普-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1023, name: 'jinpu.diffRate', label: '金普-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 庄河 (ID: 1024-1026) ---
  { id: 1024, name: 'zhuanghe.plan', label: '庄河-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1025, name: 'zhuanghe.samePeriod', label: '庄河-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1026, name: 'zhuanghe.diffRate', label: '庄河-差异率', type: 'basic', component: 'display', width: 120 },

  // --- 研究院 (ID: 1027-1029) ---
  { id: 1027, name: 'research.plan', label: '研究院-本期计划', type: 'basic', component: 'display', width: 120 },
  { id: 1028, name: 'research.samePeriod', label: '研究院-同期完成', type: 'basic', component: 'display', width: 120 },
  { id: 1029, name: 'research.diffRate', label: '研究院-差异率', type: 'basic', component: 'display', width: 120 },
];

// reportTemplate 保持不变
export const reportTemplate = [
  {
    id: 1,
    category: '气温',
    name: '月平均高温',
    unit: '℃',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 2,
    category: '气温',
    name: '月平均低温',
    unit: '℃',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 3,
    category: '设备参数',
    name: '发电机组容量',
    unit: '万kW',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 4,
    category: '设备参数',
    name: '燃煤锅炉装机容量',
    unit: 'MW',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 5,
    category: '设备参数',
    name: '电锅炉/热泵装机容量',
    unit: 'MW',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 6,
    category: '产量',
    name: '发电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 7,
    category: '产量',
    name: '供热量',
    unit: 'GJ',
    type: 'calculated',
    formula: 'VAL(8)+VAL(9)+VAL(10)+VAL(11)+VAL(12)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 8,
    category: '产量',
    name: '其中：1.供汽量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 9,
    category: '产量',
    name: '2.高温水供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 10,
    category: '产量',
    name: '3.低真空供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 11,
    category: '产量',
    name: '4.燃煤锅炉房供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 12,
    category: '产量',
    name: '5.电锅炉/热泵供热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 13,
    category: '销量',
    name: '售电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 14,
    category: '销量',
    name: '售汽量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 15,
    category: '销量',
    name: '关联交易汽量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 16,
    category: '销量',
    name: '关联交易高温水量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 17,
    category: '销量',
    name: '期末挂网面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 18,
    category: '销量',
    name: '期末供暖收费面积',
    unit: '㎡',
    type: 'calculated',
    formula: 'VAL(19)+VAL(20)+VAL(21)+VAL(22)+VAL(23)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 19,
    category: '销量',
    name: '1.汽站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 20,
    category: '销量',
    name: '2.高温水站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 21,
    category: '销量',
    name: '3.低真空站面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 22,
    category: '销量',
    name: '4.燃煤锅炉房供热面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 23,
    category: '销量',
    name: '5.电锅炉/热泵面积',
    unit: '㎡',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 24,
    category: '销量',
    name: '高温水销售量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 25,
    category: '主要物料消耗量',
    name: '生产耗原煤量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(26)+VAL(27)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 26,
    category: '主要物料消耗量',
    name: '其中：1.发电耗原煤量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 27,
    category: '主要物料消耗量',
    name: '2.供热耗原煤量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 28,
    category: '主要物料消耗量',
    name: '耗标煤总量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(29)+VAL(32)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 29,
    category: '主要物料消耗量',
    name: '其中：1.发电耗标煤量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(30)+VAL(31)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 30,
    category: '主要物料消耗量',
    name: '1.1煤折标煤耗量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 31,
    category: '主要物料消耗量',
    name: '1.2油折标煤耗量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 32,
    category: '主要物料消耗量',
    name: '2.供热耗标煤量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(33)+VAL(34)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 33,
    category: '主要物料消耗量',
    name: '2.1煤折标煤耗量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 34,
    category: '主要物料消耗量',
    name: '2.2油折标煤耗量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 35,
    category: '主要物料消耗量',
    name: '煤折标煤耗量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(30)+VAL(33)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 36,
    category: '主要物料消耗量',
    name: '耗油量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(37)+VAL(38)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 37,
    category: '主要物料消耗量',
    name: '其中：1.发电耗油量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 38,
    category: '主要物料消耗量',
    name: '2.供热耗油量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 39,
    category: '主要物料消耗量',
    name: '外购热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 40,
    category: '主要物料消耗量',
    name: '耗水量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(41)+VAL(42)+VAL(45)+VAL(46)+VAL(47)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 41,
    category: '主要物料消耗量',
    name: '其中：1.电厂耗水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 42,
    category: '主要物料消耗量',
    name: '2.电厂一次网补水量',
    unit: '吨',
    type: 'calculated',
    formula: 'VAL(43)+VAL(44)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 43,
    category: '主要物料消耗量',
    name: '2.1高温水首站补水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 44,
    category: '主要物料消耗量',
    name: '2.2低真空补水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 45,
    category: '主要物料消耗量',
    name: '3.换热站补水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 46,
    category: '主要物料消耗量',
    name: '4.燃煤锅炉房耗水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 47,
    category: '主要物料消耗量',
    name: '5.电锅炉/热泵耗水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 48,
    category: '主要物料消耗量',
    name: '耗自来水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 49,
    category: '主要物料消耗量',
    name: '耗再生水/井水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 50,
    category: '主要物料消耗量',
    name: '耗酸量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 51,
    category: '主要物料消耗量',
    name: '耗碱量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 52,
    category: '主要物料消耗量',
    name: '耗石灰石量（粗）',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 53,
    category: '主要物料消耗量',
    name: '耗石灰石粉量（细）',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 54,
    category: '主要物料消耗量',
    name: '耗氨水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 55,
    category: '主要物料消耗量',
    name: '耗氧化镁量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 56,
    category: '主要物料消耗量',
    name: '耗脱硝剂量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 57,
    category: '主要物料消耗量',
    name: '耗阻垢剂量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 58,
    category: '主要物料消耗量',
    name: '耗杀菌剂量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 59,
    category: '主要物料消耗量',
    name: '耗钢球量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 60,
    category: '主要物料消耗量',
    name: '耗天然气量',
    unit: '万m3',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 61,
    category: '主要物料消耗量',
    name: '站内耗热量',
    unit: 'GJ',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 62,
    category: '主要物料消耗量',
    name: '耗电量',
    unit: '万kWh',
    type: 'calculated',
    formula: 'VAL(63)+VAL(68)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 63,
    category: '主要物料消耗量',
    name: '综合厂用电量',
    unit: '万kWh',
    type: 'calculated',
    formula: 'VAL(64)+VAL(65)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 64,
    category: '主要物料消耗量',
    name: '其中：1.非生产厂用电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 65,
    category: '主要物料消耗量',
    name: '2.生产厂用电量',
    unit: '万kWh',
    type: 'calculated',
    formula: 'VAL(66)+VAL(67)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 66,
    category: '主要物料消耗量',
    name: '2.1发电厂用电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 67,
    category: '主要物料消耗量',
    name: '2.2供热厂用电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 68,
    category: '主要物料消耗量',
    name: '外购电量',
    unit: '万kWh',
    type: 'calculated',
    formula: 'VAL(69)+VAL(70)+VAL(71)+VAL(72)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 69,
    category: '主要物料消耗量',
    name: '其中：1.电厂外购电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 70,
    category: '主要物料消耗量',
    name: '2.燃煤锅炉房外购电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 71,
    category: '主要物料消耗量',
    name: '3.换热站外购电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 72,
    category: '主要物料消耗量',
    name: '4.电锅炉/热泵外购电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 73,
    category: '主要物料消耗量',
    name: '脱硫脱销耗水量',
    unit: '吨',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 74,
    category: '主要物料消耗量',
    name: '脱硫脱硝耗电量',
    unit: '万kWh',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 75,
    category: '比率',
    name: '生产产出率',
    unit: '%',
    type: 'calculated',
    formula: '(VAL(7)+VAL(13)*36)/29.308/VAL(28)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 76,
    category: '比率',
    name: '综合产出率',
    unit: '%',
    type: 'calculated',
    formula: '(VAL(13)*36+VAL(14)*2.952+VAL(24)+VAL(61))/29.308/VAL(28)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 77,
    category: '比率',
    name: '全厂热效率',
    unit: '%',
    type: 'calculated',
    formula: '(VAL(7)+VAL(13)*36)/(VAL(28)*29.308)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 78,
    category: '比率',
    name: '热电比',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(7)/(VAL(13)*36)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 79,
    category: '比率',
    name: '热分摊比',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(32)/VAL(28)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 80,
    category: '比率',
    name: '发电设备利用率',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(6)/VAL(3)/3744',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 81,
    category: '比率',
    name: '供热设备利用率',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(7)*1000/(VAL(4)+VAL(5))/13478400',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 82,
    category: '单耗',
    name: '综合厂用电率',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(63)/VAL(6)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 83,
    category: '单耗',
    name: '发电厂用电率',
    unit: '%',
    type: 'calculated',
    formula: 'VAL(66)/VAL(6)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 84,
    category: '单耗',
    name: '供热厂用电率',
    unit: 'kWh/GJ',
    type: 'calculated',
    formula: 'VAL(67)*10000/VAL(7)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 85,
    category: '单耗',
    name: '发电标准煤耗率',
    unit: 'g/kWh',
    type: 'calculated',
    formula: 'VAL(29)*100/VAL(6)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 86,
    category: '单耗',
    name: '供电标准煤耗率',
    unit: 'g/kWh',
    type: 'calculated',
    formula: 'VAL(29)*100/(VAL(6)-VAL(66))',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 87,
    category: '单耗',
    name: '供热标准煤耗率',
    unit: 'kg/GJ',
    type: 'calculated',
    formula: 'VAL(32)*1000/VAL(7)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 88,
    category: '单耗',
    name: '发电水耗率',
    unit: '吨/万kWh',
    type: 'calculated',
    formula: '(VAL(41)-VAL(8))*(1-VAL(79))/VAL(6)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 89,
    category: '单耗',
    name: '供热水耗率',
    unit: '吨/GJ',
    type: 'calculated',
    formula: '((VAL(41)-VAL(8))*VAL(79)+VAL(8))/VAL(7)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 90,
    category: '单耗',
    name: '供暖热耗率',
    unit: 'GJ/㎡',
    type: 'calculated',
    formula: 'VAL(61)/VAL(18)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 91,
    category: '单耗',
    name: '供暖水耗率',
    unit: 'kg/㎡',
    type: 'calculated',
    formula: '(VAL(42)+VAL(45)+VAL(46)+VAL(47))*1000/VAL(18)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 92,
    category: '单耗',
    name: '供暖电耗率',
    unit: 'kWh/㎡',
    type: 'calculated',
    formula: '(VAL(70)+VAL(71)+VAL(72))*10000/VAL(18)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 93,
    category: '其它',
    name: '入炉煤低位发热量',
    unit: 'kJ/kg',
    type: 'calculated',
    formula: 'VAL(35)/VAL(25)*29308',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 94,
    category: '经济指标',
    name: '供热发电收入',
    unit: '万元',
    type: 'calculated',
    formula: 'VAL(95)+VAL(97)+VAL(99)+VAL(101)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 95,
    category: '经济指标',
    name: '暖收入',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 96,
    category: '经济指标',
    name: '暖单价',
    unit: '元/㎡',
    type: 'calculated',
    formula: 'VAL(95)*10000/VAL(18)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 97,
    category: '经济指标',
    name: '电收入',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 98,
    category: '经济指标',
    name: '电单价',
    unit: '元/kWh',
    type: 'calculated',
    formula: 'VAL(97)/VAL(13)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 99,
    category: '经济指标',
    name: '售汽收入',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 100,
    category: '经济指标',
    name: '汽平均单价',
    unit: '元/吨',
    type: 'calculated',
    formula: 'VAL(99)*10000/VAL(14)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 101,
    category: '经济指标',
    name: '售高温水收入',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 102,
    category: '经济指标',
    name: '高温水平均单价',
    unit: '元/GJ',
    type: 'calculated',
    formula: 'VAL(101)*10000/VAL(24)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 103,
    category: '经济指标',
    name: '购热成本',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 104,
    category: '经济指标',
    name: '热单价',
    unit: '元/GJ',
    type: 'calculated',
    formula: 'VAL(103)*10000/VAL(39)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 105,
    category: '经济指标',
    name: '煤成本',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 106,
    category: '经济指标',
    name: '标煤单价',
    unit: '元/吨',
    type: 'calculated',
    formula: 'VAL(105)*10000/VAL(28)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 107,
    category: '经济指标',
    name: '购电成本',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
  {
    id: 108,
    category: '经济指标',
    name: '购电单价',
    unit: '元/kWh',
    type: 'calculated',
    formula: 'VAL(107)/VAL(68)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
  {
    id: 109,
    category: '经济指标',
    name: '水成本',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
    {
    id: 110,
    category: '经济指标',
    name: '水单价',
    unit: '元/吨',
    type: 'calculated',
    formula: 'VAL(109)*10000/VAL(42)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
    {
    id: 111,
    category: '经济指标',
    name: '劳务费',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: false,
  },
    {
    id: 112,
    category: '经济指标',
    name: '抢修费',
    unit: '万元',
    type: 'basic',
    formula: null,
    style: { fontWeight: 'normal' },
    samePeriodEditable: true,
  },
  {
    id: 113,
    category: '经济指标',
    name: '毛利',
    unit: '万元',
    type: 'calculated',
    formula: 'VAL(94)-VAL(103)-VAL(105)-VAL(107)-VAL(109)-VAL(111)-VAL(112)',
    style: { fontWeight: 'bold' },
    samePeriodEditable: false,
  },
];